import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css"
import { BudgetsProvider } from "../contexts/BudgetsContext"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tracking My Money',
  description: 'Generated by Majed',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BudgetsProvider>
        {children}
        </BudgetsProvider>
        </body>
    </html>
  )
}
